# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml"
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version (Forge for 1.16.5 is version 36)
loaderVersion="[36,)"
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="All Rights Reserved"
# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/Daellhin/RealisticSolar"

[[mods]]
modId="realisticsolar"
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
version="0.1.0"
displayName="Realistic Solar"
author="Daellhin"
description='''
This is a mod for Minecraft I made to get a better
understanding of Java and Minecraft.
The mod will add solar panels and the machines
to produce them in a realistic manner.

This mod is still in the early stages of developement.
'''

[[dependencies.realisticsolar]]
    modId="forge"
    mandatory=true
    versionRange="[36,)" 
    ordering="NONE"
    side="BOTH"

[[dependencies.realisticsolar]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,]"
    ordering="NONE"
    side="BOTH"