modLoader="javafml"
loaderVersion="[26,)"
issueTrackerURL="https://github.com/Daellhin/RealisticSolar"

[[mods]]
modId="realisticsolar"
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
version="0.1.0"
displayName="Realistic Solar"
author="Daellhin"
description='''
This is a mod for Minecraft I made to get a better
understanding of Java and Minecraft.
The mod will add solar panels and the machines
to produce them in a realistic manner.

This mod is still in the early stages of developement.
'''

[[dependencies.realisticsolar]]
    modId="forge"
    mandatory=true
    versionRange="[26,)" 
    ordering="NONE"
    side="BOTH"

[[dependencies.realisticsolar]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.3]"
    ordering="NONE"
    side="BOTH"